### ISSUE TITLE
Anpassung anzeige NEPviewerCR_get_todays_energy.sh

### ISSUE THREAD

**Issue by KosoTheOne** [DE-cr/NEPviewerCR#1]
Hi, ist es möglich den Perl Code so anzupassen das er mir die aktuelle power und die kw/h anzeigt und das nur mit Uhrzeit ohne Datum?

Liebe Grüße

**Comment by KosoTheOne** [comment]
perl -n00e 'use POSIX qw(strftime); print join(" kWh on ", /(?:Today):([-.: \d]+)/g), " KW/H um ", strftime("%H:%M", localtime), "\n"'

So wird die akutelle KW/H Zahl zur aktuellen Uhrzeit angeben, jetzt wäre noch interesannt ob die Power auch abgegriffen werden kann

**Comment by DE-cr** [comment]
Hallo KosoTheOne,
was Du mit _"ob die Power auch abgegriffen werden kann"_ meinst, verstehe ich nicht.
Wenn Du die letzten in die Cloud gesendeten Werte haben willst, probier' mal folgendes:
```
perl -p00e '
  ($w) = /round\((\d+)/;
  ($k) = /Today:(.+?)\(/;
  ($t) = /update.+? (.+?)"/;
  $_ = "$w W / $k kWh at $t\n";'
```
Grüße,
-cr

**Comment by KosoTheOne** [comment]
Hallo CR,

besten dank. das war genau was ich gesucht habe!
FYI: Mit "ob die Power auch abgegriffen werden kann" habe ich gemeint wie viel W aktuell geliefert wird. 

Grüße
KosoTheOne

**Comment by DE-cr** [comment]
Freut mich, dass ich Dir helfen konnte, KosoTheOne.
